name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-java:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build JAR with Gradle
      run: ./gradlew clean build jar

    - name: Debug Build Output
      run: ls -lah build/libs/ || echo "build/libs/ directory does not exist!"

    - name: Ensure Build Directory Exists
      run: mkdir -p build/libs && touch build/libs/dummy.jar

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: tinayanxu/github-action-demo
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
